---

namespace: 'ansibleguy'
name: 'opnsense'
version: 1.2.16
readme: 'README.md'
authors:
  - 'OXL IT Services <contact+opnsense@OXL.at>'
description: "Ansible Collection to manage OPNSense firewalls using their API"
license_file: 'LICENSE.txt'
tags:
  - 'firewall'
  - 'api'
  - 'opnsense'
  - 'iac'
  - 'network'
  - 'security'
  - 'filter'
dependencies: {}
repository: 'https://github.com/O-X-L/ansible_opnsense'
documentation: 'https://ansible-opnsense.oxl.app'
homepage: 'https://www.OXL.at'
issues: 'https://github.com/O-X-L/ansible_opnsense/issues'
build_ignore: ['*_pytest.py', '*_testdata.py']
