---

name: Functional-Tests Execution for PRs

on:
  pull_request:
    branches: [latest]
    paths:
      - 'plugins/**.py'
      - 'tests/**.yml'
      - '.github/workflows/functional_test_pr.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Test Connection
        run: |
          sudo apt install curl >/dev/null
          https_proxy=${{ secrets.CI_TEST_PROXY }} curl --fail-with-body https://${{ vars.CI_TEST_FIREWALL_1 }} --insecure > /tmp/test.html

          if grep -q 'DNS Rebind attack' < /tmp/test.html
          then
            echo 'ERROR: Firewall Hostname ${{ vars.CI_TEST_FIREWALL_1 }} not configured!'
            exit 1
          fi
        shell: bash

      - name: Query changes
        run: |
          echo "Branch: '${GITHUB_REF#refs/heads/}'"

          commit_latest="$(git merge-base latest ${GITHUB_REF#refs/heads/})"
          echo "Commit latest: '${commit_latest}'"

          commit_pr="$(git rev-parse HEAD)"
          echo "Commit PR: '${commit_pr}'"

          git diff --name-only "$commit_latest" "$commit_pr" > /tmp/changes.txt
          echo "Changed files:"
          cat /tmp/changes.txt
        shell: bash


