---

name: Functional-Tests Execution for PRs

on:
  pull_request:
    branches: [latest]
    paths:
      - 'plugins/**.py'
      - 'tests/**.yml'
      - '.github/workflows/functional_test_pr.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Test Connection
        run: |
          sudo apt install curl >/dev/null
          https_proxy=${{ secrets.CI_TEST_PROXY }} curl --fail-with-body https://${{ vars.CI_TEST_FIREWALL_1 }} --insecure > /tmp/test.html

          if grep -q 'DNS Rebind attack' < /tmp/test.html
          then
            echo 'ERROR: Firewall Hostname ${{ vars.CI_TEST_FIREWALL_1 }} not configured!'
            exit 1
          fi
        shell: bash

      - name: Get changes
        id: pr_changed_files
        uses: tj-actions/changed-files@v46

      - name: Checking which module to test
        id: modules_to_test
        run: |
          echo ${{ steps.pr_changed_files.outputs.all_changed_files }} > /tmp/changes.txt
          python3 scripts/get_changed_modules.py /tmp/changes.txt /tmp/changed_modules.txt

          count="$(cat /tmp/changed_modules.txt | wc -l)"

          echo "count=${count}" >> $GITHUB_OUTPUT
          if [[ "$count" == "0" ]]
          then
            echo 'INFO: NO MODULES REQUIRE TESTING!'
          else
            echo "INFO: MODULES TO TEST = ${count}"
          fi
        shell: bash

      - name: Install test-dependencies
        run: pip install -r requirements_test.txt > /dev/null
        shell: bash
        if: "${{ steps.modules_to_test.outputs.module_count != '0' }}"

      - name: Running Integration-Tests
        run: bash scripts/test_pr.sh
        shell: bash
        if: "${{ steps.modules_to_test.outputs.count != '0' }}"
        environment:
          TEST_FIREWALL: ${{ vars.CI_TEST_FIREWALL_1 }}
          TEST_API_KEY: ${{ secrets.CI_TEST_API_CREDENTIALS }}
          TEST_PROXY: ${{ secrets.CI_TEST_PROXY }}
